# -*- coding: utf-8 -*-
"""BoT-Sort+ReID.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gpAJFHfussRzRlRWYZz-K8aMvpVLVn9E
"""

import cv2
import os
import numpy as np
import torch
import torch.nn as nn
from torchvision import transforms, models
from PIL import Image
from ultralytics import YOLO
from datetime import datetime
from tqdm import tqdm
from collections import defaultdict, deque
import gc
import logging
import json
from typing import Dict, List, Tuple, Optional
import traceback
import subprocess
import sys
import pandas as pd
import matplotlib
matplotlib.use('Agg')  # Non-interactive backend for production
import matplotlib.pyplot as plt
from sklearn.metrics import precision_recall_curve, average_precision_score

# ============= ULTRALYTICS UPDATE CHECK =============
def ensure_ultralytics_updated():
    """Ensure Ultralytics is up-to-date for ReID support"""
    try:
        import ultralytics
        print(f"Current Ultralytics version: {ultralytics.__version__}")

        version_parts = ultralytics.__version__.split('.')
        major, minor = int(version_parts[0]), int(version_parts[1])

        if major < 8 or (major == 8 and minor < 3):
            print("⚠ Updating Ultralytics for ReID support...")
            subprocess.check_call([sys.executable, "-m", "pip", "install", "-U", "ultralytics", "-q"])
            print("✓ Ultralytics updated successfully")
        else:
            print("✓ Ultralytics version is compatible")
    except Exception as e:
        print(f"⚠ Could not verify/update Ultralytics: {e}")
        print("Proceeding anyway...")

ensure_ultralytics_updated()


# ============= LOGGING SETUP =============
def setup_logging(log_dir: str = "logs") -> logging.Logger:
    """Setup structured logging for production"""
    os.makedirs(log_dir, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    logger = logging.getLogger("StoreAnalytics")
    logger.setLevel(logging.INFO)
    logger.handlers.clear()

    fh = logging.FileHandler(f"{log_dir}/analytics_{timestamp}.log")
    fh.setLevel(logging.INFO)
    ch = logging.StreamHandler()
    ch.setLevel(logging.INFO)

    formatter = logging.Formatter('%(asctime)s - %(levelname)s - %(message)s')
    fh.setFormatter(formatter)
    ch.setFormatter(formatter)

    logger.addHandler(fh)
    logger.addHandler(ch)

    return logger


# ============= OPTIMIZED CONFIG FOR CROWDED SCENES =============
class Config:
    def __init__(self, config_path: Optional[str] = None):
        if config_path and os.path.exists(config_path):
            with open(config_path, 'r') as f:
                config = json.load(f)
            self._load_from_dict(config)
        else:
            self._load_defaults()

    def _load_defaults(self):
        # Models
        self.YOLO_MODEL = "yolo11x.pt"
        self.RESNET_MODEL = "/content/multihead_resnet50_model3.pth"

        # ===== OPTIMIZED FOR CROWDED SCENES =====
        self.CONFIDENCE = 0.28  # LOWER for better crowd detection
        self.IOU_THRESHOLD = 0.45  # LOWER for better separation
        self.IMG_SIZE = 1280  # HIGHER resolution for better detection
        self.MAX_DET = 500  # INCREASED for crowds

        # ===== CLASSIFICATION WITH ETHNICITY FALLBACK =====
        self.CLASSIFY_EVERY_N_FRAMES = 3  # More frequent
        self.CLASSIFICATION_CONFIDENCE_THRESHOLD = 0.55  # Balanced threshold
        self.ETHNICITY_CONFIDENCE_THRESHOLD = 0.40  # Lower threshold for ethnicity
        self.ETHNICITY_UNKNOWN_FALLBACK = True  # Assign "unknown" if low confidence
        self.KEEP_CLASSIFICATION_FRAMES = 400  # Longer persistence

        # Multi-frame voting for better accuracy
        self.CLASSIFICATION_BUFFER_SIZE = 5  # Collect 5 predictions
        self.MIN_VOTES_FOR_LOCK = 3  # Need 3 consistent predictions

        # ===== ENHANCED TRACK STABILITY =====
        self.MIN_DETECTIONS_FOR_CLASSIFICATION = 3
        self.RECLASSIFY_IF_LOST_FRAMES = 60

        # ===== BOT-SORT WITH ENHANCED REID =====
        self.TRACKER_CONFIG = "botsort_reid_enhanced.yaml"
        self.ENABLE_REID = True

        # ReID parameters for better ID maintenance
        self.TRACK_BUFFER = 90  # Keep tracks for 3 seconds
        self.TRACK_HIGH_THRESH = 0.4  # Lower for crowds
        self.TRACK_LOW_THRESH = 0.05  # Very low for partial visibility
        self.NEW_TRACK_THRESH = 0.5
        self.MATCH_THRESH = 0.7  # More lenient matching

        # ReID specific
        self.PROXIMITY_THRESH = 0.3  # More lenient spatial matching
        self.APPEARANCE_THRESH = 0.18  # More lenient appearance matching
        self.REID_WEIGHT = 0.65  # Higher weight on appearance

        # Memory
        self.CLEANUP_EVERY = 120
        self.BBOX_SMOOTHING_ALPHA = 0.75
        self.ENABLE_SMOOTHING = True

        # ===== NEW: LABEL SMOOTHING =====
        self.LABEL_SMOOTHING_ALPHA = 0.7  # Smooth label positions
        self.ENABLE_LABEL_SMOOTHING = True

        # Device
        self.DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

        # Colors (BGR format)
        self.COLORS = {
            'male': (255, 100, 0),
            'female': (255, 0, 255),
            'unknown': (0, 255, 0),
            'entrance': (255, 0, 0),
            'store': (0, 0, 255),
            'exit': (0, 255, 255),
            'passby_box': (0, 255, 0),
            'counter_bg': (40, 40, 40),
            'counter_text': (255, 255, 255),
            'lost_track': (128, 128, 128)
        }

        # Production
        self.ENABLE_TRACK_DEBUG = True
        self.SAVE_FAILED_FRAMES = False

    def _load_from_dict(self, config: dict):
        for key, value in config.items():
            setattr(self, key, value)

    def validate(self) -> Tuple[bool, List[str]]:
        errors = []
        if not os.path.exists(self.YOLO_MODEL):
            errors.append(f"YOLO model not found: {self.YOLO_MODEL}")
        if self.RESNET_MODEL and not os.path.exists(self.RESNET_MODEL):
            errors.append(f"ResNet model not found: {self.RESNET_MODEL}")
        return len(errors) == 0, errors

    def create_tracker_config(self):
        """Create enhanced BoT-SORT config optimized for crowded scenes"""

        if self.ENABLE_REID:
            config_content = f"""# Enhanced BoT-SORT with ReID - Optimized for Crowded Scenes
# Configuration for better ID maintenance and occlusion handling

tracker_type: botsort

# OPTIMIZED detection thresholds for crowds
track_high_thresh: {self.TRACK_HIGH_THRESH}
track_low_thresh: {self.TRACK_LOW_THRESH}
new_track_thresh: {self.NEW_TRACK_THRESH}

# Enhanced track management
track_buffer: {self.TRACK_BUFFER}
match_thresh: {self.MATCH_THRESH}

# Camera motion compensation (crucial for moving people)
gmc_method: sparseOptFlow

# ===== ENHANCED REID CONFIGURATION =====
with_reid: True
proximity_thresh: {self.PROXIMITY_THRESH}
appearance_thresh: {self.APPEARANCE_THRESH}
fuse_score: True
model: auto

# Balanced weights - favor appearance over motion
lambda_iou: 0.35
lambda_reid: 0.65

# Additional parameters
reid_weights: null
fast_reid: False

# Minimum box area (filter out tiny detections)
min_box_area: 400
aspect_ratio_thresh: 4.0
"""
        else:
            config_content = """# BoT-SORT without ReID (fallback)

tracker_type: botsort
track_high_thresh: 0.5
track_low_thresh: 0.1
new_track_thresh: 0.6
track_buffer: 60
match_thresh: 0.8
gmc_method: sparseOptFlow
with_reid: False
"""

        os.makedirs("configs", exist_ok=True)
        config_path = f"configs/{self.TRACKER_CONFIG}"
        with open(config_path, 'w') as f:
            f.write(config_content)

        return config_path


# ============= RESNET MODEL =============
class MultiHeadResNet50(nn.Module):
    def __init__(self, num_gender, num_age, num_ethnicity):
        super().__init__()
        self.resnet = models.resnet50(weights=None)
        num_ftrs = self.resnet.fc.in_features
        self.resnet.fc = nn.Identity()

        self.shared_features = nn.Sequential(
            nn.Linear(num_ftrs, 1024), nn.ReLU(), nn.BatchNorm1d(1024), nn.Dropout(0.3),
            nn.Linear(1024, 512), nn.ReLU(), nn.BatchNorm1d(512), nn.Dropout(0.3)
        )
        self.gender_head = nn.Sequential(
            nn.Linear(512, 256), nn.ReLU(), nn.Dropout(0.2), nn.Linear(256, num_gender)
        )
        self.age_head = nn.Sequential(
            nn.Linear(512, 256), nn.ReLU(), nn.Dropout(0.2), nn.Linear(256, num_age)
        )
        self.ethnicity_head = nn.Sequential(
            nn.Linear(512, 256), nn.ReLU(), nn.Dropout(0.2), nn.Linear(256, num_ethnicity)
        )

    def forward(self, x):
        x = self.resnet(x)
        x = self.shared_features(x)
        return self.gender_head(x), self.age_head(x), self.ethnicity_head(x)


# ============= ENHANCED CLASSIFIER WITH ETHNICITY FALLBACK =============
class AttributeClassifier:
    def __init__(self, model_path: str, device: torch.device, logger: logging.Logger, config: Config):
        self.device = device
        self.logger = logger
        self.config = config

        self.logger.info("Loading ResNet Classifier...")
        checkpoint = torch.load(model_path, map_location=device, weights_only=False)
        checkpoint_config = checkpoint['config']

        self.gender_classes = checkpoint_config['gender_classes']
        self.age_classes = checkpoint_config['age_classes']
        self.ethnicity_classes = checkpoint_config['ethnicity_classes']

        self.model = MultiHeadResNet50(
            checkpoint_config['num_gender_classes'],
            checkpoint_config['num_age_classes'],
            checkpoint_config['num_ethnicity_classes']
        ).to(device)

        self.model.load_state_dict(checkpoint['model_state_dict'])
        self.model.eval()

        self.transform = transforms.Compose([
            transforms.Resize((224, 224)),
            transforms.ToTensor(),
            transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
        ])

        self.classification_count = 0
        self.failed_classifications = 0
        self.ethnicity_unknown_count = 0

    @torch.no_grad()
    def classify(self, image: np.ndarray) -> Optional[Dict]:
        """Classify with ethnicity fallback to 'unknown' if low confidence"""
        try:
            if image.size == 0 or image.shape[0] < 40 or image.shape[1] < 40:
                self.failed_classifications += 1
                return None

            # Check image quality
            gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
            blur = cv2.Laplacian(gray, cv2.CV_64F).var()
            if blur < 25:  # Very low threshold for crowds
                self.failed_classifications += 1
                return None

            img_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
            img_pil = Image.fromarray(img_rgb)
            img_tensor = self.transform(img_pil).unsqueeze(0).to(self.device)

            gender_out, age_out, ethnicity_out = self.model(img_tensor)

            gender_probs = torch.softmax(gender_out, 1)
            age_probs = torch.softmax(age_out, 1)
            ethnicity_probs = torch.softmax(ethnicity_out, 1)

            gender_conf, gender_pred = torch.max(gender_probs, 1)
            age_conf, age_pred = torch.max(age_probs, 1)
            ethnicity_conf, ethnicity_pred = torch.max(ethnicity_probs, 1)

            # ===== ETHNICITY FALLBACK LOGIC =====
            ethnicity_class = self.ethnicity_classes[ethnicity_pred.item()]
            ethnicity_confidence = ethnicity_conf.item()

            # If ethnicity confidence is too low, assign "unknown"
            if self.config.ETHNICITY_UNKNOWN_FALLBACK and ethnicity_confidence < self.config.ETHNICITY_CONFIDENCE_THRESHOLD:
                ethnicity_class = "unknown"
                ethnicity_confidence = 1.0  # Set to 1.0 for "unknown"
                self.ethnicity_unknown_count += 1

            self.classification_count += 1

            return {
                'gender': {'class': self.gender_classes[gender_pred.item()], 'confidence': gender_conf.item()},
                'age': {'class': self.age_classes[age_pred.item()], 'confidence': age_conf.item()},
                'ethnicity': {'class': ethnicity_class, 'confidence': ethnicity_confidence}
            }
        except Exception as e:
            self.logger.error(f"Classification error: {e}")
            self.failed_classifications += 1
            return None

    def get_stats(self) -> Dict:
        """Return classification statistics"""
        total = self.classification_count + self.failed_classifications
        return {
            'total_classifications': self.classification_count,
            'failed_classifications': self.failed_classifications,
            'ethnicity_unknown_assigned': self.ethnicity_unknown_count,
            'success_rate': (self.classification_count / total * 100) if total > 0 else 0
        }


# ============= ENHANCED TRACK MANAGER WITH MULTI-FRAME VOTING =============
class TrackManager:
    """Manages track history with persistent classifications and multi-frame voting"""
    def __init__(self, config: Config, logger: logging.Logger):
        self.config = config
        self.logger = logger

        # Track data structure
        self.tracks = {}
        self.classification_persistence = {}

        # Multi-frame classification buffers
        self.classification_buffer = defaultdict(lambda: {
            'gender': deque(maxlen=config.CLASSIFICATION_BUFFER_SIZE),
            'age': deque(maxlen=config.CLASSIFICATION_BUFFER_SIZE),
            'ethnicity': deque(maxlen=config.CLASSIFICATION_BUFFER_SIZE)
        })

        # NEW: Label position smoothing cache
        self.label_positions = {}

        # Statistics
        self.stats = {
            'tracks_created': 0,
            'tracks_classified': 0,
            'classifications_recovered': 0,
            'tracks_lost': 0,
            'reid_assists': 0,
            'id_switches_prevented': 0
        }

    def update_track(self, track_id: int, frame_num: int):
        """Update track information"""
        if track_id not in self.tracks:
            self.tracks[track_id] = {
                'first_seen': frame_num,
                'last_seen': frame_num,
                'detections': 1,
                'classification': None,
                'classification_locked': False,
                'classification_frame': None,
                'reid_maintained': False,
                'gap_count': 0
            }
            self.stats['tracks_created'] += 1
        else:
            prev_last_seen = self.tracks[track_id]['last_seen']
            gap = frame_num - prev_last_seen

            self.tracks[track_id]['last_seen'] = frame_num
            self.tracks[track_id]['detections'] += 1

            # Detect if ReID maintained the ID (gap > 20 frames)
            if gap > 20:
                self.tracks[track_id]['gap_count'] += 1

                if not self.tracks[track_id]['reid_maintained'] and gap > 30:
                    self.tracks[track_id]['reid_maintained'] = True
                    self.stats['reid_assists'] += 1
                    self.stats['id_switches_prevented'] += 1

                    if self.config.ENABLE_TRACK_DEBUG:
                        self.logger.info(f"🔍 ReID maintained Track {track_id} after {gap} frame gap")

    def smooth_label_position(self, track_id: int, bbox: Tuple[int, int, int, int]) -> Tuple[int, int]:
        """Smooth label position to avoid jitter"""
        x1, y1, x2, y2 = bbox
        current_pos = (x1, y1)

        if not self.config.ENABLE_LABEL_SMOOTHING:
            return current_pos

        if track_id not in self.label_positions:
            self.label_positions[track_id] = current_pos
            return current_pos

        # Exponential smoothing
        prev_x, prev_y = self.label_positions[track_id]
        alpha = self.config.LABEL_SMOOTHING_ALPHA

        smooth_x = int(alpha * x1 + (1 - alpha) * prev_x)
        smooth_y = int(alpha * y1 + (1 - alpha) * prev_y)

        smoothed = (smooth_x, smooth_y)
        self.label_positions[track_id] = smoothed

        return smoothed

    def add_classification_vote(self, track_id: int, classification: Dict):
        """Add a classification vote to the buffer"""
        buffer = self.classification_buffer[track_id]
        buffer['gender'].append(classification['gender'])
        buffer['age'].append(classification['age'])
        buffer['ethnicity'].append(classification['ethnicity'])

    def get_voted_classification(self, track_id: int) -> Optional[Dict]:
        """Get classification through confidence-weighted voting"""
        if track_id not in self.classification_buffer:
            return None

        buffer = self.classification_buffer[track_id]

        # Need minimum votes
        if len(buffer['gender']) < self.config.MIN_VOTES_FOR_LOCK:
            return None

        def weighted_vote(predictions):
            """Vote by summing confidences for each class"""
            if not predictions:
                return None

            votes = defaultdict(float)
            for pred in predictions:
                votes[pred['class']] += pred['confidence']

            if not votes:
                return None

            winner = max(votes.items(), key=lambda x: x[1])
            avg_confidence = winner[1] / len(predictions)

            return {'class': winner[0], 'confidence': avg_confidence}

        voted = {
            'gender': weighted_vote(buffer['gender']),
            'age': weighted_vote(buffer['age']),
            'ethnicity': weighted_vote(buffer['ethnicity'])
        }

        # Check if all categories have votes
        if any(v is None for v in voted.values()):
            return None

        return voted

    def set_classification(self, track_id: int, classification: Dict, frame_num: int):
        """Lock classification for a track (PERMANENT)"""
        if track_id in self.tracks:
            self.tracks[track_id]['classification'] = classification
            self.tracks[track_id]['classification_locked'] = True
            self.tracks[track_id]['classification_frame'] = frame_num
            self.stats['tracks_classified'] += 1

            # Store in persistence cache
            self.classification_persistence[track_id] = {
                'classification': classification,
                'frame': frame_num
            }

            if self.config.ENABLE_TRACK_DEBUG:
                gender = classification['gender']['class']
                ethnicity = classification['ethnicity']['class']
                self.logger.info(f"✓ Track {track_id} LOCKED: {gender}, {ethnicity}")

    def get_classification(self, track_id: int, current_frame: int) -> Optional[Dict]:
        """Get classification for a track with persistence"""
        # First check if track has locked classification
        if track_id in self.tracks and self.tracks[track_id].get('classification_locked'):
            return self.tracks[track_id]['classification']

        # Check persistence cache
        if track_id in self.classification_persistence:
            cached = self.classification_persistence[track_id]
            frames_since = current_frame - cached['frame']

            if frames_since < self.config.KEEP_CLASSIFICATION_FRAMES:
                if self.config.ENABLE_TRACK_DEBUG and frames_since > 60:
                    self.logger.info(f"✓ Track {track_id} classification recovered ({frames_since} frames gap)")
                    self.stats['classifications_recovered'] += 1
                return cached['classification']

        return None

    def should_classify(self, track_id: int, frame_num: int) -> bool:
        """Determine if track should be classified now"""
        if track_id not in self.tracks:
            return False

        track = self.tracks[track_id]

        # Don't re-classify if locked
        if track.get('classification_locked'):
            return False

        # Need minimum detections
        if track['detections'] < self.config.MIN_DETECTIONS_FOR_CLASSIFICATION:
            return False

        # If never classified, yes
        if track['classification'] is None:
            return True

        # If lost for too long, re-classify
        if track['classification_frame'] is not None:
            frames_since = frame_num - track['classification_frame']
            if frames_since > self.config.RECLASSIFY_IF_LOST_FRAMES:
                return True

        return False

    def cleanup(self, current_frame: int):
        """Remove very old tracks"""
        dead_ids = []
        for track_id, track in self.tracks.items():
            age = current_frame - track['last_seen']
            if age > 600:  # 20 seconds at 30fps
                dead_ids.append(track_id)
                if track.get('classification_locked') and self.config.ENABLE_TRACK_DEBUG:
                    self.logger.warning(f"✗ Track {track_id} removed (age: {age} frames)")
                    self.stats['tracks_lost'] += 1

        for track_id in dead_ids:
            del self.tracks[track_id]
            if track_id in self.classification_buffer:
                del self.classification_buffer[track_id]
            if track_id in self.label_positions:
                del self.label_positions[track_id]

    def get_stats(self) -> Dict:
        return {
            'active_tracks': len(self.tracks),
            **self.stats
        }


# ============= HELPERS =============
def validate_zones(zones: Dict[str, List]) -> Tuple[bool, List[str]]:
    errors = []
    for zone_name in ['entrance', 'store', 'exit']:
        if zone_name not in zones:
            errors.append(f"Missing zone: {zone_name}")
        elif len(zones[zone_name]) < 3:
            errors.append(f"Zone '{zone_name}' needs 3+ points")
    return len(errors) == 0, errors


def point_in_zone(cx: int, cy: int, polygon: List) -> bool:
    try:
        pts = np.array(polygon, dtype=np.int32)
        return cv2.pointPolygonTest(pts, (int(cx), int(cy)), False) >= 0
    except:
        return False


def draw_zone(frame: np.ndarray, polygon: List, color: Tuple, label: str):
    try:
        pts = np.array(polygon, dtype=np.int32).reshape((-1, 1, 2))
        cv2.polylines(frame, [pts], True, color, 2)
        cv2.putText(frame, label, tuple(polygon[0]), cv2.FONT_HERSHEY_SIMPLEX, 0.7, color, 2)
    except:
        pass


def smooth_bbox(prev_bbox: Optional[Tuple], new_bbox: Tuple, alpha: float = 0.75) -> Tuple:
    if prev_bbox is None:
        return new_bbox
    try:
        prev = np.array(prev_bbox, dtype=float)
        new = np.array(new_bbox, dtype=float)
        smoothed = alpha * new + (1 - alpha) * prev
        return tuple(smoothed.astype(int))
    except:
        return new_bbox


# ============= GROUND TRUTH ANALYZER =============
class GroundTruthAnalyzer:
    """Collects detection data for comprehensive analytics"""
    def __init__(self):
        self.detections = []
        self.frame_stats = defaultdict(lambda: {'total_detections': 0, 'high_conf_detections': 0})

    def add_detection(self, frame_num: int, track_id: int, bbox: Tuple, confidence: float,
                     in_zone: bool, classification: Optional[Dict] = None):
        """Record a detection for later analysis"""
        x1, y1, x2, y2 = bbox
        bbox_area = (x2 - x1) * (y2 - y1)

        self.detections.append({
            'frame': frame_num,
            'track_id': track_id,
            'x1': x1,
            'y1': y1,
            'x2': x2,
            'y2': y2,
            'bbox_area': bbox_area,
            'confidence': confidence,
            'in_store_zone': in_zone,
            'gender': classification['gender']['class'] if classification else 'unknown',
            'age': classification['age']['class'] if classification else 'unknown',
            'ethnicity': classification['ethnicity']['class'] if classification else 'unknown',
            'gender_conf': classification['gender']['confidence'] if classification else 0.0,
            'age_conf': classification['age']['confidence'] if classification else 0.0,
            'ethnicity_conf': classification['ethnicity']['confidence'] if classification else 0.0
        })

        # Track per-frame statistics
        self.frame_stats[frame_num]['total_detections'] += 1
        if confidence >= 0.5:
            self.frame_stats[frame_num]['high_conf_detections'] += 1

    def export_to_csv(self, output_path: str):
        """Export detections to CSV with full details"""
        df = pd.DataFrame(self.detections)
        df.to_csv(output_path, index=False)
        return df

    def generate_comprehensive_analytics(self, output_dir: str, video_name: str):
        """Generate multiple analytics plots and metrics"""
        if not self.detections:
            return {}

        df = pd.DataFrame(self.detections)
        metrics = {}

        # ===== 1. DETECTION CONFIDENCE DISTRIBUTION =====
        plt.figure(figsize=(12, 5))

        plt.subplot(1, 2, 1)
        plt.hist(df['confidence'], bins=50, color='steelblue', edgecolor='black', alpha=0.7)
        plt.xlabel('Detection Confidence', fontsize=11)
        plt.ylabel('Frequency', fontsize=11)
        plt.title('YOLO Detection Confidence Distribution', fontsize=12, fontweight='bold')
        plt.axvline(df['confidence'].mean(), color='red', linestyle='--',
                   label=f'Mean = {df["confidence"].mean():.3f}')
        plt.axvline(df['confidence'].median(), color='green', linestyle='--',
                   label=f'Median = {df["confidence"].median():.3f}')
        plt.legend()
        plt.grid(True, alpha=0.3)

        # ===== 2. CONFIDENCE BY ZONE =====
        plt.subplot(1, 2, 2)
        in_store = df[df['in_store_zone'] == True]['confidence']
        outside = df[df['in_store_zone'] == False]['confidence']

        plt.boxplot([in_store, outside], labels=['In Store', 'Outside Store'])
        plt.ylabel('Detection Confidence', fontsize=11)
        plt.title('Detection Confidence by Zone', fontsize=12, fontweight='bold')
        plt.grid(True, alpha=0.3, axis='y')

        plt.tight_layout()
        conf_dist_path = f"{output_dir}/{video_name}_confidence_analysis.png"
        plt.savefig(conf_dist_path, dpi=150, bbox_inches='tight')
        plt.close()

        metrics['confidence_distribution_plot'] = conf_dist_path

        # ===== 3. PRECISION-RECALL CURVE (Per-Detection Quality) =====
        # We'll use high confidence (>0.5) as "positive" detection quality indicator
        y_true = (df['confidence'] >= 0.5).astype(int)
        y_scores = df['confidence'].values

        precision, recall, thresholds = precision_recall_curve(y_true, y_scores)
        ap = average_precision_score(y_true, y_scores) if len(np.unique(y_true)) > 1 else 0.0

        plt.figure(figsize=(10, 6))
        plt.plot(recall, precision, linewidth=2.5, label=f'AP = {ap:.3f}', color='darkblue')
        plt.fill_between(recall, precision, alpha=0.2, color='blue')
        plt.xlabel('Recall', fontsize=12)
        plt.ylabel('Precision', fontsize=12)
        plt.title('Precision-Recall Curve - YOLO Detection Quality', fontsize=14, fontweight='bold')
        plt.grid(True, alpha=0.3)
        plt.legend(fontsize=12, loc='upper right')

        # Add confidence threshold markers
        conf_thresholds = [0.3, 0.5, 0.7]
        for ct in conf_thresholds:
            idx = np.argmin(np.abs(thresholds - ct)) if len(thresholds) > 0 else 0
            if idx < len(recall) and idx < len(precision):
                plt.scatter(recall[idx], precision[idx], s=100, marker='o',
                          label=f'conf={ct}', zorder=5)

        plt.legend(fontsize=10)
        plt.tight_layout()
        pr_path = f"{output_dir}/{video_name}_precision_recall.png"
        plt.savefig(pr_path, dpi=150, bbox_inches='tight')
        plt.close()

        metrics['precision_recall_plot'] = pr_path
        metrics['average_precision'] = float(ap)

        # ===== 4. DETECTION STATISTICS =====
        metrics['detection_stats'] = {
            'total_detections': len(df),
            'unique_tracks': df['track_id'].nunique(),
            'mean_confidence': float(df['confidence'].mean()),
            'median_confidence': float(df['confidence'].median()),
            'std_confidence': float(df['confidence'].std()),
            'min_confidence': float(df['confidence'].min()),
            'max_confidence': float(df['confidence'].max()),
            'high_confidence_detections': int((df['confidence'] >= 0.7).sum()),
            'medium_confidence_detections': int(((df['confidence'] >= 0.5) & (df['confidence'] < 0.7)).sum()),
            'low_confidence_detections': int((df['confidence'] < 0.5).sum()),
            'in_store_detections': int(df['in_store_zone'].sum()),
            'outside_store_detections': int((~df['in_store_zone']).sum())
        }

        # ===== 5. DETECTIONS OVER TIME =====
        plt.figure(figsize=(14, 5))

        frames = sorted(self.frame_stats.keys())
        total_per_frame = [self.frame_stats[f]['total_detections'] for f in frames]
        high_conf_per_frame = [self.frame_stats[f]['high_conf_detections'] for f in frames]

        plt.subplot(1, 2, 1)
        plt.plot(frames, total_per_frame, linewidth=1.5, label='All Detections', color='steelblue')
        plt.plot(frames, high_conf_per_frame, linewidth=1.5, label='High Conf (≥0.5)', color='darkgreen')
        plt.xlabel('Frame Number', fontsize=11)
        plt.ylabel('Detections per Frame', fontsize=11)
        plt.title('Detection Count Over Time', fontsize=12, fontweight='bold')
        plt.legend()
        plt.grid(True, alpha=0.3)

        # ===== 6. CLASSIFICATION CONFIDENCE DISTRIBUTION =====
        classified = df[df['gender'] != 'unknown']
        if len(classified) > 0:
            plt.subplot(1, 2, 2)
            plt.hist(classified['gender_conf'], bins=30, alpha=0.6, label='Gender', color='blue')
            plt.hist(classified['age_conf'], bins=30, alpha=0.6, label='Age', color='green')
            plt.hist(classified['ethnicity_conf'], bins=30, alpha=0.6, label='Ethnicity', color='orange')
            plt.xlabel('Classification Confidence', fontsize=11)
            plt.ylabel('Frequency', fontsize=11)
            plt.title('Classification Confidence Distribution', fontsize=12, fontweight='bold')
            plt.legend()
            plt.grid(True, alpha=0.3)

        plt.tight_layout()
        timeline_path = f"{output_dir}/{video_name}_timeline_analysis.png"
        plt.savefig(timeline_path, dpi=150, bbox_inches='tight')
        plt.close()

        metrics['timeline_plot'] = timeline_path

        # ===== 7. TRACK PERSISTENCE ANALYSIS =====
        track_lengths = df.groupby('track_id').size()

        plt.figure(figsize=(10, 6))
        plt.hist(track_lengths, bins=50, color='coral', edgecolor='black', alpha=0.7)
        plt.xlabel('Track Length (frames)', fontsize=11)
        plt.ylabel('Number of Tracks', fontsize=11)
        plt.title('Track Persistence Distribution', fontsize=12, fontweight='bold')
        plt.axvline(track_lengths.mean(), color='red', linestyle='--',
                   label=f'Mean = {track_lengths.mean():.1f} frames')
        plt.axvline(track_lengths.median(), color='green', linestyle='--',
                   label=f'Median = {track_lengths.median():.1f} frames')
        plt.legend()
        plt.grid(True, alpha=0.3)
        plt.tight_layout()

        track_persist_path = f"{output_dir}/{video_name}_track_persistence.png"
        plt.savefig(track_persist_path, dpi=150, bbox_inches='tight')
        plt.close()

        metrics['track_persistence_plot'] = track_persist_path
        metrics['track_stats'] = {
            'mean_track_length': float(track_lengths.mean()),
            'median_track_length': float(track_lengths.median()),
            'max_track_length': int(track_lengths.max()),
            'min_track_length': int(track_lengths.min())
        }

        return metrics


# ============= MAIN SYSTEM =============
class StoreAnalytics:
    def __init__(self, config: Config, logger: logging.Logger):
        self.config = config
        self.logger = logger

        self.logger.info("="*70)
        self.logger.info("OPTIMIZED STORE ANALYTICS - CROWDED SCENE SPECIALIST")
        self.logger.info("="*70)
        self.logger.info(f"Device: {self.config.DEVICE}")
        self.logger.info(f"ReID: {'ENABLED' if self.config.ENABLE_REID else 'DISABLED'}")
        self.logger.info(f"Ethnicity Fallback: {'ENABLED' if self.config.ETHNICITY_UNKNOWN_FALLBACK else 'DISABLED'}")
        self.logger.info(f"Label Smoothing: {'ENABLED' if self.config.ENABLE_LABEL_SMOOTHING else 'DISABLED'}")

        # Validate config
        is_valid, errors = self.config.validate()
        if not is_valid:
            for error in errors:
                self.logger.error(error)
            raise ValueError("Invalid configuration")

        # Create tracker config
        try:
            tracker_path = self.config.create_tracker_config()
            self.logger.info(f"✓ Enhanced BoT-SORT config: {tracker_path}")
        except Exception as e:
            self.logger.error(f"Failed to create tracker config: {e}")
            raise

        if torch.cuda.is_available():
            torch.cuda.empty_cache()
        gc.collect()

        # Load YOLO
        self.logger.info("Loading YOLO Model...")
        self.yolo = YOLO(self.config.YOLO_MODEL)
        self.logger.info(f"✓ YOLO loaded (conf={self.config.CONFIDENCE}, iou={self.config.IOU_THRESHOLD})")

        # Load Classifier
        self.classifier = None
        if os.path.exists(self.config.RESNET_MODEL):
            try:
                self.classifier = AttributeClassifier(
                    self.config.RESNET_MODEL,
                    self.config.DEVICE,
                    self.logger,
                    self.config
                )
                self.logger.info("✓ Classifier loaded with ethnicity fallback")
            except Exception as e:
                self.logger.warning(f"Classifier failed: {e}")

        # Track manager
        self.track_manager = TrackManager(self.config, self.logger)

        # Ground truth analyzer
        self.gt_analyzer = GroundTruthAnalyzer()

        self.headless = "/content" in os.getcwd()
        if not self.headless:
            cv2.namedWindow("Analytics", cv2.WINDOW_NORMAL)

        self.logger.info("="*70)

    def _draw_ui(self, frame, footfall, passby, unique, male_count, female_count, track_stats):
        """Draw enhanced UI with statistics"""
        panel_width = 380
        panel_height = 360
        px, py = 20, 20

        overlay = frame.copy()
        cv2.rectangle(overlay, (px, py), (px + panel_width, py + panel_height),
                     self.config.COLORS['counter_bg'], -1)
        cv2.addWeighted(overlay, 0.75, frame, 0.25, 0, frame)
        cv2.rectangle(frame, (px, py), (px + panel_width, py + panel_height), (255, 255, 255), 2)

        font = cv2.FONT_HERSHEY_DUPLEX
        y = py + 35

        cv2.putText(frame, "ANALYTICS PRO", (px + 15, y), font, 0.7, (0, 255, 255), 2)
        y += 20
        cv2.line(frame, (px + 10, y), (px + panel_width - 10, y), (255, 255, 255), 1)

        y += 30
        cv2.putText(frame, f"Footfall:", (px + 15, y), font, 0.6, (200, 200, 200), 1)
        cv2.putText(frame, f"{footfall}", (px + 250, y), font, 0.75, (0, 255, 255), 2)

        y += 30
        cv2.putText(frame, f"Pass-by:", (px + 15, y), font, 0.6, (200, 200, 200), 1)
        cv2.putText(frame, f"{passby}", (px + 250, y), font, 0.75, (0, 255, 0), 2)

        y += 30
        cv2.putText(frame, f"Unique:", (px + 15, y), font, 0.6, (200, 200, 200), 1)
        cv2.putText(frame, f"{unique}", (px + 250, y), font, 0.75, (255, 0, 255), 2)

        y += 35
        cv2.line(frame, (px + 10, y), (px + panel_width - 10, y), (100, 100, 100), 1)
        y += 20

        cv2.putText(frame, "TRACKING (ReID):", (px + 15, y), font, 0.55, (0, 255, 200), 1)
        y += 22
        cv2.putText(frame, f"Active: {track_stats['active_tracks']}", (px + 15, y), font, 0.5, (255, 255, 255), 1)
        y += 20
        cv2.putText(frame, f"Locked: {track_stats['tracks_classified']}", (px + 15, y), font, 0.5, (0, 255, 0), 1)
        y += 20
        cv2.putText(frame, f"ReID Saves: {track_stats['reid_assists']}", (px + 15, y), font, 0.5, (0, 200, 255), 1)
        y += 20
        cv2.putText(frame, f"Recovered: {track_stats['classifications_recovered']}", (px + 15, y), font, 0.5, (255, 200, 0), 1)

        total = male_count + female_count
        if total > 0:
            y += 30
            cv2.line(frame, (px + 10, y), (px + panel_width - 10, y), (100, 100, 100), 1)
            y += 20

            male_pct = male_count / total * 100
            female_pct = female_count / total * 100

            cv2.putText(frame, f"Male: {male_count}", (px + 15, y), font, 0.6, (255, 100, 0), 1)
            cv2.putText(frame, f"{male_pct:.1f}%", (px + 250, y), font, 0.6, (255, 100, 0), 2)

            y += 25
            cv2.putText(frame, f"Female: {female_count}", (px + 15, y), font, 0.6, (255, 0, 255), 1)
            cv2.putText(frame, f"{female_pct:.1f}%", (px + 250, y), font, 0.6, (255, 0, 255), 2)

        return frame

    def _draw_label(self, frame, bbox, attributes, track_id, is_locked=False):
        """Draw classification label with SMOOTH positioning"""
        x1, y1, x2, y2 = bbox

        # Get smoothed label position
        label_x, label_y = self.track_manager.smooth_label_position(track_id, bbox)

        gender = attributes['gender']['class'].lower()
        color = self.config.COLORS.get(gender, self.config.COLORS['unknown'])

        # Thicker border if locked
        thickness = 4 if is_locked else 3
        cv2.rectangle(frame, (x1, y1), (x2, y2), color, thickness)

        lines = [
            f"ID: {track_id}{'*' if is_locked else ''}",
            attributes['gender']['class'].capitalize(),
            attributes['age']['class'].replace('_', ' ').title(),
            attributes['ethnicity']['class'].replace('_', ' ').title()
        ]

        font = cv2.FONT_HERSHEY_SIMPLEX
        y_offset = label_y - 10

        for line in lines:
            # Shadow
            cv2.putText(frame, line, (label_x+1, y_offset+1), font, 0.5, (0,0,0), 2)
            # Text
            cv2.putText(frame, line, (label_x, y_offset), font, 0.5, color, 2)
            y_offset -= 18

        return frame

    def process_video(self, video_path: str, zones: Dict) -> Dict:
        """Process video with optimized tracking and ground truth collection"""
        start_time = datetime.now()

        is_valid, errors = validate_zones(zones)
        if not is_valid:
            raise ValueError(f"Invalid zones: {errors}")

        cap = cv2.VideoCapture(video_path)
        if not cap.isOpened():
            raise ValueError(f"Cannot open: {video_path}")

        fps = int(cap.get(cv2.CAP_PROP_FPS))
        width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
        height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
        total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

        self.logger.info(f"Video: {video_path}")
        self.logger.info(f"{width}x{height} @ {fps}fps, {total_frames} frames")

        # Output
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        os.makedirs("output", exist_ok=True)
        video_name = os.path.splitext(os.path.basename(video_path))[0]
        out_video = f"output/{video_name}_{timestamp}_optimized.mp4"
        out_json = f"output/{video_name}_{timestamp}_optimized.json"
        out_csv = f"output/{video_name}_{timestamp}_detections.csv"

        writer = cv2.VideoWriter(out_video, cv2.VideoWriter_fourcc(*'mp4v'), fps, (width, height))

        entrance = zones['entrance']
        store = zones['store']
        exit_zone = zones['exit']

        # State
        person_states = {}
        footfall_ids = set()
        passby_ids = set()
        unique_visitors = set()
        bbox_cache = {}

        male_count = female_count = 0
        stats = {'gender': defaultdict(int), 'age': defaultdict(int), 'ethnicity': defaultdict(int)}

        self.logger.info("🚀 Processing with optimized crowd detection...")
        pbar = tqdm(total=total_frames, unit="f")

        frame_num = 0
        tracking_errors = 0

        while True:
            try:
                ret, frame = cap.read()
                if not ret:
                    break

                if frame_num % self.config.CLEANUP_EVERY == 0:
                    gc.collect()
                    if torch.cuda.is_available():
                        try:
                            torch.cuda.empty_cache()
                        except:
                            pass
                    self.track_manager.cleanup(frame_num)

                # ===== OPTIMIZED TRACKING =====
                try:
                    results = self.yolo.track(
                        frame,
                        conf=self.config.CONFIDENCE,
                        iou=self.config.IOU_THRESHOLD,
                        imgsz=self.config.IMG_SIZE,
                        tracker=f"configs/{self.config.TRACKER_CONFIG}",
                        persist=True,
                        verbose=False,
                        classes=[0],
                        max_det=self.config.MAX_DET
                    )
                except Exception as track_error:
                    tracking_errors += 1
                    if tracking_errors == 1:
                        self.logger.error(f"Tracking error: {track_error}")
                    frame_num += 1
                    pbar.update(1)
                    continue

                # Draw zones
                draw_zone(frame, entrance, self.config.COLORS['entrance'], "ENTRANCE")
                draw_zone(frame, store, self.config.COLORS['store'], "STORE")
                draw_zone(frame, exit_zone, self.config.COLORS['exit'], "EXIT")

                # Process tracks
                if results[0].boxes is not None and results[0].boxes.id is not None:
                    boxes = results[0].boxes.xyxy.cpu().numpy()
                    track_ids = results[0].boxes.id.cpu().numpy().astype(int)
                    confidences = results[0].boxes.conf.cpu().numpy()

                    for i, track_id in enumerate(track_ids):
                        x1, y1, x2, y2 = map(int, boxes[i])
                        confidence = float(confidences[i])

                        # Update track manager
                        self.track_manager.update_track(track_id, frame_num)

                        # Smooth bbox
                        if self.config.ENABLE_SMOOTHING:
                            prev = bbox_cache.get(track_id)
                            smoothed = smooth_bbox(prev, (x1, y1, x2, y2), self.config.BBOX_SMOOTHING_ALPHA)
                            x1, y1, x2, y2 = smoothed
                            bbox_cache[track_id] = smoothed

                        cx = int((x1 + x2) / 2)
                        cy = int((y1 + y2) / 2)

                        in_entrance = point_in_zone(cx, cy, entrance)
                        in_store = point_in_zone(cx, cy, store)
                        in_exit = point_in_zone(cx, cy, exit_zone)

                        # State logic
                        state = person_states.get(track_id, "")
                        if state == "":
                            if in_entrance:
                                person_states[track_id] = "entrance"
                                passby_ids.add(track_id)
                            elif in_store:
                                person_states[track_id] = "rejected"
                        elif state == "entrance" and in_store:
                            person_states[track_id] = "in_store"
                            footfall_ids.add(track_id)
                            if track_id in passby_ids:
                                passby_ids.remove(track_id)

                        is_visitor = (track_id in footfall_ids) and (in_store or in_exit)

                        # Record detection for ground truth analysis
                        classification = self.track_manager.get_classification(track_id, frame_num)
                        self.gt_analyzer.add_detection(
                            frame_num, track_id, (x1, y1, x2, y2), confidence,
                            is_visitor, classification
                        )

                        if is_visitor:
                            # Get existing classification (persistent!)
                            is_locked = classification is not None and track_id in self.track_manager.tracks and \
                                       self.track_manager.tracks[track_id].get('classification_locked', False)

                            # If not locked, try to classify
                            if not is_locked and self.classifier:
                                if frame_num % self.config.CLASSIFY_EVERY_N_FRAMES == 0:
                                    if self.track_manager.should_classify(track_id, frame_num):
                                        crop = frame[y1:y2, x1:x2]
                                        if crop.size > 0:
                                            attrs = self.classifier.classify(crop)
                                            if attrs:
                                                # Add to voting buffer
                                                self.track_manager.add_classification_vote(track_id, attrs)

                                                # Check if we have enough votes to lock
                                                voted = self.track_manager.get_voted_classification(track_id)
                                                if voted:
                                                    # Check overall confidence
                                                    avg_conf = (voted['gender']['confidence'] +
                                                               voted['age']['confidence'] +
                                                               voted['ethnicity']['confidence']) / 3

                                                    if avg_conf >= self.config.CLASSIFICATION_CONFIDENCE_THRESHOLD:
                                                        # LOCK IT
                                                        self.track_manager.set_classification(track_id, voted, frame_num)
                                                        classification = voted
                                                        is_locked = True

                                                        # Count unique visitor
                                                        if track_id not in unique_visitors:
                                                            unique_visitors.add(track_id)
                                                            stats['gender'][voted['gender']['class']] += 1
                                                            stats['age'][voted['age']['class']] += 1
                                                            stats['ethnicity'][voted['ethnicity']['class']] += 1

                                                            if voted['gender']['class'].lower() == 'male':
                                                                male_count += 1
                                                            elif voted['gender']['class'].lower() == 'female':
                                                                female_count += 1

                            # Draw with classification
                            if classification:
                                self._draw_label(frame, (x1, y1, x2, y2), classification, track_id, is_locked)
                            else:
                                cv2.rectangle(frame, (x1, y1), (x2, y2), self.config.COLORS['unknown'], 2)
                                cv2.putText(frame, f"ID: {track_id}", (x1, y1-10),
                                          cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255,255,255), 2)

                        elif in_entrance or (track_id in passby_ids and track_id not in footfall_ids):
                            cv2.rectangle(frame, (x1, y1), (x2, y2), self.config.COLORS['passby_box'], 2)
                            cv2.putText(frame, f"ID: {track_id}", (x1, y1-10),
                                      cv2.FONT_HERSHEY_SIMPLEX, 0.5, self.config.COLORS['passby_box'], 2)

                # Draw UI
                track_stats = self.track_manager.get_stats()
                self._draw_ui(frame, len(footfall_ids), len(passby_ids),
                             len(unique_visitors), male_count, female_count, track_stats)

                writer.write(frame)

                if not self.headless:
                    cv2.imshow("Analytics", cv2.resize(frame, (1280, 720)))
                    if cv2.waitKey(1) & 0xFF == ord('q'):
                        break

                frame_num += 1
                pbar.update(1)

            except Exception as e:
                self.logger.error(f"Frame {frame_num}: {e}")
                frame_num += 1
                pbar.update(1)
                continue

        cap.release()
        writer.release()
        pbar.close()
        if not self.headless:
            cv2.destroyAllWindows()

        duration = (datetime.now() - start_time).total_seconds()

        # ===== EXPORT GROUND TRUTH DATA =====
        self.logger.info("\n📊 Generating comprehensive analytics...")

        # Export CSV
        detections_df = self.gt_analyzer.export_to_csv(out_csv)
        self.logger.info(f"✓ Detections exported: {out_csv}")
        self.logger.info(f"  Total detections: {len(detections_df)}")

        # Generate comprehensive analytics
        analytics_metrics = self.gt_analyzer.generate_comprehensive_analytics("output", video_name + f"_{timestamp}")
        if analytics_metrics:
            self.logger.info(f"\n✓ Analytics generated:")
            self.logger.info(f"  Detection confidence: mean={analytics_metrics['detection_stats']['mean_confidence']:.3f}, "
                           f"median={analytics_metrics['detection_stats']['median_confidence']:.3f}")
            self.logger.info(f"  High confidence detections (≥0.7): {analytics_metrics['detection_stats']['high_confidence_detections']}")
            self.logger.info(f"  Average track length: {analytics_metrics['track_stats']['mean_track_length']:.1f} frames")
            self.logger.info(f"  Files created:")
            for key, path in analytics_metrics.items():
                if key.endswith('_plot'):
                    self.logger.info(f"    - {path}")

        # Report
        total = male_count + female_count
        classifier_stats = self.classifier.get_stats() if self.classifier else {}

        report = {
            'video': video_name,
            'tracker': 'BoT-SORT + ReID (Optimized)',
            'processing_time': duration,
            'fps': round(frame_num / duration, 1) if duration > 0 else 0,
            'footfall': len(footfall_ids),
            'passby': len(passby_ids),
            'unique': len(unique_visitors),
            'male': male_count,
            'male_pct': round(male_count / total * 100, 1) if total > 0 else 0,
            'female': female_count,
            'female_pct': round(female_count / total * 100, 1) if total > 0 else 0,
            'total_classified': total,
            'demographics': dict(stats),
            'tracking': track_stats,
            'classifier': classifier_stats,
            'tracking_errors': tracking_errors,
            'analytics_metrics': analytics_metrics if analytics_metrics else {},
            'config': {
                'confidence': self.config.CONFIDENCE,
                'iou': self.config.IOU_THRESHOLD,
                'ethnicity_fallback': self.config.ETHNICITY_UNKNOWN_FALLBACK,
                'label_smoothing': self.config.ENABLE_LABEL_SMOOTHING
            },
            'output_files': {
                'video': out_video,
                'detections_csv': out_csv,
                'analytics_plots': [v for k, v in analytics_metrics.items() if k.endswith('_plot')] if analytics_metrics else [],
                'report_json': out_json
            }
        }

        with open(out_json, 'w') as f:
            json.dump(report, f, indent=2)

        self.logger.info(f"\n✅ Complete! {report['fps']} FPS")
        self.logger.info(f"Output: {out_video}")
        self.logger.info(f"Footfall: {len(footfall_ids)} | Unique: {len(unique_visitors)}")
        self.logger.info(f"Male: {male_count} ({report['male_pct']}%) | Female: {female_count} ({report['female_pct']}%)")
        self.logger.info(f"Locked: {track_stats['tracks_classified']} | ReID Assists: {track_stats['reid_assists']}")

        if self.classifier:
            self.logger.info(f"Ethnicity 'unknown' assigned: {classifier_stats.get('ethnicity_unknown_assigned', 0)}")

        return report


# ============= MAIN =============
if __name__ == "__main__":
    logger = setup_logging()

    try:
        config = Config()

        ZONES = {
            'entrance': [[266, 348], [350, 822], [1924, 692], [1998, 324]],
            'store': [[14, 850], [14, 1136], [2246, 912], [2204, 662]],
            'exit': [[8, 1138], [34, 1430], [2526, 1420], [2342, 912]]
        }

        system = StoreAnalytics(config, logger)
        report = system.process_video("test.mp4", ZONES)

        logger.info("="*70)
        logger.info("✅ OPTIMIZED SYSTEM COMPLETE")
        logger.info("="*70)

    except Exception as e:
        logger.critical(f"FATAL: {e}")
        logger.critical(traceback.format_exc())
        raise